# Copyright 2018 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/android/channel.gni")
import("//build/config/android/config.gni")

declare_args() {
  # Show a launcher icon to open WebView developer UI. This is enabled by
  # default for all prestable builds. The icon for Monochrome is shown
  # dynamically at runtime if Monochrome is the current selected system WebView
  # implementation or hidden otherwise.
  webview_devui_show_icon = android_channel != "stable"
  # `android_resources` dependency that contains the application icon.
  webview_icon_resources = "icon_resources"
  # Icon resource ID without the leading '@', e.g. `drawable/icon_webview`.
  webview_icon_resource_id = ""
  # Application label, e.g. `Android System WebView`.
  webview_application_label = ""
}

system_webview_android_manifest =
    "$root_gen_dir/android_webview/system_webview_apk/AndroidManifest.xml"
system_webview_64_android_manifest =
    "$root_gen_dir/android_webview/system_webview_64_apk/AndroidManifest.xml"
trichrome_webview_android_manifest =
    "$root_gen_dir/android_webview/trichrome_webview_apk/AndroidManifest.xml"
trichrome_webview_64_android_manifest =
    "$root_gen_dir/android_webview/trichrome_webview_64_apk/AndroidManifest.xml"
trichrome_webview_64_32_android_manifest = "$root_gen_dir/android_webview/trichrome_webview_64_32_apk/AndroidManifest.xml"
trichrome_webview_32_android_manifest =
    "$root_gen_dir/android_webview/trichrome_webview_32_apk/AndroidManifest.xml"

upstream_only_webview_deps = [
  "//android_webview:platform_service_bridge_upstream_implementation_java",
  "//android_webview/nonembedded:$webview_icon_resources",
]

webview_product_config_java_package = "org.chromium.android_webview"
